name: Deploy Frontend

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Deploy Frontend to Server
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST << 'EOF'
          # Создаем директорию для приложения
          mkdir -p ~/frontend-app && cd ~/frontend-app
          echo  ${GIT_TOKEN}
          echo ${GIT_USERNAME}
          # Загружаем репозиторий
          if [ -d "showdown-front" ]; then
              cd showdown-front && git pull || exit 1
          else
              git clone https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/SulavkoPavel/showdown-front.git showdown-front || exit 1
              cd showdown-front
          fi

          # Собираем Docker образ
          if [ -f Dockerfile ]; then
              docker build -t frontend-app -f Dockerfile .
          else
              echo "Dockerfile не найден!"
              exit 1
          fi

          # Удаляем старый контейнер
          docker stop frontend-container || true
          docker rm frontend-container || true

          # Запускаем новый контейнер
          docker run -d -p 81:3000 --name frontend-container frontend-app
          EOF
